### ISSUE TITLE
error starting

### ISSUE THREAD

**Issue by Faustyu1** [Gml-Launcher/Gml.Launcher#32]
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\Users\anytk\AppData\Roaming\123\runtime\java-runtime-gamma\bin\javaw.exe' with working directory 'C:\Users\anytk\AppData\Roaming\123\clients\Create'. Не удается найти указанный файл.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Gml.Launcher.ViewModels.Pages.OverviewPageViewModel.<>c__DisplayClass55_0.<<StartGame>b__0>d.MoveNext() in C:\Users\anytk\Downloads\main - 1\Gml.Launcher-main\src\Gml.Launcher\ViewModels\Pages\OverviewPageViewModel.cs:line 139

вот мне только так остается писать
![image](https://github.com/Gml-Launcher/Gml.Launcher/assets/104709162/50be8512-1c59-4bfd-9e9f-711bbfb938cf)

main ветка

**Comment by GamerVII-NET** [comment]
Gml.Backend какой версии?

**Comment by Faustyu1** [comment]
обновлял 3 часа назад

**Comment by GamerVII-NET** [comment]
Ошибка может возникнуть, если профиль загрузился не полностью, либо на стороне Gml.Backend, либо на стороне лаунчера.

1) Проверь, что профиль загружен полностью
2) Перекачай профиль на Gml.Backend (Кнопка запгрузить в профиле)
3) Собери профиль (Кнопка собрать в профиле)
4) Нажми "Играть" в лаунчере.

Если это не поможет вам решить ошибку, обращайся

**Comment by Faustyu1** [comment]
![image](https://github.com/Gml-Launcher/Gml.Launcher/assets/104709162/34ae656e-8421-4bc6-985f-60efc715bf65)
он просто не хочет загружаться

**Comment by GamerVII-NET** [comment]
Если ты не загрузишь профиль, он не будет установлен.


Что пишет в консоли в web-socket подключении? 
![image](https://github.com/Gml-Launcher/Gml.Launcher/assets/111225722/b9590724-b5e5-4d54-b1cc-d754c192b360)

**Comment by Faustyu1** [comment]
![image](https://github.com/Gml-Launcher/Gml.Launcher/assets/104709162/00402b4b-8275-49df-8d45-53d9c85f056c)

**Comment by Faustyu1** [comment]
![image](https://github.com/Gml-Launcher/Gml.Launcher/assets/104709162/88413c06-12a6-4f5c-a1c8-ec883c16769f)

**Comment by GamerVII-NET** [comment]
У тебя старая версия фронтенд части, обновись до версии:
https://github.com/Gml-Launcher/Gml.Backend/releases/tag/v0.1.0-alpha4

Скрипт обновления представлен тут: https://github.com/Gml-Launcher/Gml.Backend.Installer/

**Comment by Faustyu1** [comment]
так там написано обновление гмл бекенд а ты мне говоришь фронтенд обновить

**Comment by Faustyu1** [comment]
> обновлял 3 часа назад скриптом

я вчера только обновлял бекенд

**Comment by GamerVII-NET** [comment]
> так там написано обновление гмл бекенд а ты мне говоришь фронтенд обновить

Нужно комплексно обновить все компоненты системы, а не по отдельности. Пожалуйста, запустите скрипт обновления

**Comment by AuthFailed** [comment]
Плюс, та же сложность с jawaw.exe. Профиль собран с веткой dev

**Comment by GamerVII-NET** [comment]
> Плюс, та же сложность с jawaw.exe. Профиль собран с веткой dev

Уточните версию Minecraft, загрузчик, производили ли вы повторную загрузку и сборку профиля, а так же место установки Gml.Backend.
